spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hospital
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: hospital

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka